apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print
            image: busybox:stable
            args: ['echo', 'this is a test']
          restartPolicy: Never
      backoffLimit: 4
      activeDeadlineSeconds: 10